server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forum
    username: forum_user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.mail: DEBUG
    javax.mail: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type: TRACE

profiles:
  active: dev


  mail:
    host: localhost
    port: 1025
#    username: hello
#    password: hello

    properties:
      mail:
        smtp:
          #          ssl:
          #            trust: "*"
          auth: false
          starttls:
            enable: false
          connection timeout: 5000
          timeout: 3000
          write timeout: 5000

#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update



#spring.application.name=forum-service
#
#spring.data.mongodb.uri=${MONGODB_URI}
